name: Terraform Infrastructure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest

    outputs:
      terraform_plan: ${{ steps.plan.outputs.stdout }}

    steps:
      - uses: actions/checkout@v3

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - uses: hashicorp/setup-terraform@v2

      - run: terraform init
        working-directory: ./terraform

      - id: plan
        env:
          TF_AUTO_VARS: ${{ secrets.TF_AUTO_VARS }}
        run: |
          echo "$TF_AUTO_VARS" > terraform.auto.tfvars

          terraform plan -no-color -input=false
        working-directory: ./terraform

      - run: echo ${{ steps.plan.outputs.stdout }}
      - run: echo ${{ steps.plan.outputs.stderr }}
      - run: echo ${{ steps.plan.outputs.exitcode }}

  apply:
    name: "Apply"
    needs: plan
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: |
          echo "$TF_AUTO_VARS" > terraform.auto.tfvars
          terraform apply -input=false -auto-approve
        env:
          PLAN: "terraform\n${{ needs.plan.outputs.terraform_plan }}"
          TF_AUTO_VARS: ${{ secrets.TF_AUTO_VARS }}
